---
- hosts: all
  become: true
  tasks: 


  - name: install apache2 package on Ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php    
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



  - name: install httpd package on Fedora
    ansible.builtin.dnf:
      name: 
        - httpd
        - php
      use_backend: dnf4
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"

