  - name: create user
    tags: always
    ansible.builtin.user:
      name: joemomma
      groups: root

  - name: add sudoers file for joemomma
    tags: always
    ansible.builtin.copy:
      src: sudoer_joemomma
      dest: /etc/sudoers.d/joemomma
      group: root
      mode: 0440

  - name: add sshe for joemomma user
    tags: always
    ansible.builtin.authorized_key:
      user: joemomma
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOFOK1KQ0kW8IjsftVyzkvopTqaoPuv3PSMjQWiEb8p5 mschrein@ubuntu-WS"


    
